### ISSUE TITLE
Failed to open configuration file config.yaml open config.yaml: The system connot find the file specified.

### ISSUE THREAD

**Issue by Donotinvert** [hpool-dev/aleo-miner#7]
显示无法找到配置文件，config.yaml与软件在同一目录下，执行程序显示“Failed to open configuration file config.yaml open config.yaml: The system connot find the file specified.”，管理员身份执行同样报此错误，下方是我的配置。
```
# miner名称，不填使用电脑名
# miner name, use the computer name without filling in
minerName:aaa1
# 在 https://www.hpool.in/center/configuration 找ApiKey
# Find ApiKey at https://www.hpool.in/center/configuration
apiKey: "aleo0000-xxxx-xxxxxxxxxxxxxxxxxxx"
# 日志配置
# Log configuration
log:
  level: info
  file: miner.log
# x-proxy配置
# x-proxy configuration
server:
  # 一个局域网内，代理只需要开一台就可以了，如代理所在的机器Ip是192.168.1.88，端口9190
  # 下面配置改为
  # xproxy: "http://192.168.1.88:9190"
  # In a local area network, only one proxy is required. For example, the IP of the machine where the proxy is located is 192.168.1.88 and the port is 9190
  # The following configuration is changed to
  # xproxy: "http://192.168.1.88:9190"
  xproxy: "http://192.168.1.74:9190"
# socket 或者是http代理配置
# socket5 or http proxy
proxy:
    # E.g http://127.0.0.1:8888 socket5://127.0.0.1:8888
    url: ""
    username: ""
    password: ""

# 参数配置
# Parameter configuration
extraParams:
    # 设备编号，多设备0,1,2,3
    # Device number, multi-device 0,1,2,3
    devices: 0,1

    # 任务数
    # task parallel number
    taskParallel: 10

    # 流并发数
    # streamNums
    streamNums: 10

    # 任务线程数
    # threads
    taskThreads: 8

    # CPU绑定间隔
    # CPU binding step
    cpuAffinityStep: 2

    # cpu开始绑定编号
    # cpu start binding number
    cpuAffinityStart: 0

```
